SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH like '%-03-%'
      AND TLNO IS NOT NULL
      AND GENDER ='W'
ORDER BY MEMBER_ID;